#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Market Trends — Controller worktree setup.
#
# Runs once when a new worktree is created. Installs dependencies for the
# shared, server, and web workspaces (shared first, since server & web link it
# via `file:../shared`), and writes a self-contained `.env` at the worktree root
# so the API boots with the stub provider + in-memory store (no Postgres, no
# network needed).
#
# Idempotent: safe to re-run manually. An existing `.env` is left untouched so
# user tweaks are preserved.
# ─────────────────────────────────────────────────────────────────────────────
set -e

# ── ports (Controller provides PORT_OFFSET; validate before arithmetic) ───────
API_BASE_PORT="${MARKET_TRENDS_API_BASE_PORT:-8987}"
CLIENT_BASE_PORT="${MARKET_TRENDS_WEB_BASE_PORT:-5273}"
OFFSET="${PORT_OFFSET:-0}"

if ! [[ "$API_BASE_PORT" =~ ^[0-9]+$ ]]; then
  echo "API_BASE_PORT must be a number (got: $API_BASE_PORT)" >&2
  exit 1
fi
if ! [[ "$CLIENT_BASE_PORT" =~ ^[0-9]+$ ]]; then
  echo "CLIENT_BASE_PORT must be a number (got: $CLIENT_BASE_PORT)" >&2
  exit 1
fi
if ! [[ "$OFFSET" =~ ^[0-9]+$ ]]; then
  echo "PORT_OFFSET must be a number (got: $OFFSET)" >&2
  exit 1
fi

API_PORT=$((API_BASE_PORT + OFFSET))
WEB_PORT=$((CLIENT_BASE_PORT + OFFSET))

# ── install dependencies (shared first — server & web resolve it via file:link) ─
# Each workspace ships its own package-lock.json, so prefer `npm ci` for
# reproducible installs and fall back to `npm install` if the lock is missing.
install_ws() {
  local dir="$1"
  if [ -f "$dir/package-lock.json" ]; then
    ( cd "$dir" && npm ci )
  else
    ( cd "$dir" && npm install )
  fi
}

echo "[setup] installing shared …"
install_ws shared
echo "[setup] installing server …"
install_ws server
echo "[setup] installing web …"
install_ws web

# ── worktree-local .env (server loads ../.env relative to server/) ─────────────
# Inherit the main tree's .env verbatim (so every env var — present and future —
# propagates to worktrees automatically), then override only PORT to give this
# worktree a unique API port. An existing worktree .env is left untouched so user
# tweaks are preserved.
if [ -f ".env" ]; then
  echo "[setup] .env already exists — leaving it untouched."
else
  SOURCE_ENV=""
  if [ -n "${SOURCE_PATH:-}" ] && [ -f "$SOURCE_PATH/.env" ]; then
    SOURCE_ENV="$SOURCE_PATH/.env"
  elif [ -n "${SOURCE_PATH:-}" ] && [ -f "$SOURCE_PATH/.env.example" ]; then
    SOURCE_ENV="$SOURCE_PATH/.env.example"
  elif [ -f ".env.example" ]; then
    # Main worktree fallback (SOURCE_PATH may equal WORKTREE_PATH).
    SOURCE_ENV=".env.example"
  fi

  if [ -n "$SOURCE_ENV" ]; then
    cp "$SOURCE_ENV" .env
    # Replace an uncommented PORT= line, or append one if absent/commented.
    if grep -qE "^\s*PORT\s*=" .env; then
      sed -i.bak -E "s/^\s*PORT\s*=.*/PORT=$API_PORT/" .env && rm -f .env.bak
    else
      printf '\n# Worktree port (set by setup.sh, unique per worktree)\nPORT=%s\n' "$API_PORT" >> .env
    fi
    echo "[setup] copied .env from $SOURCE_ENV, set PORT=$API_PORT."
  else
    # No source to inherit from — write a minimal self-contained .env.
    cat > .env <<EOF
# Generated by .coding-orchestrator/setup.sh for worktree "${WORKTREE_NAME:-main}".
PORT=$API_PORT
MARKET_DATA_PROVIDER=stub
CACHE_TTL_SECONDS=3600
EOF
    echo "[setup] no source .env found — wrote minimal .env (PORT=$API_PORT, stub, in-memory)."
  fi
fi

echo "[setup] done. API → :$API_PORT  web → :$WEB_PORT"
